export const FETCH_TUTORIALS = 'FETCH_TUTORIALS';

export const REGISTRATE = 'REGISTRATE';
export const LOGIN = 'LOGIN';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_TUTORIALS = 'UPDATE_TUTORIALS';